### ISSUE TITLE
Services in generated manifest are not understood by UV

### ISSUE THREAD

**Issue by abollini** [dbmdz/iiif-presentation-api#10]
We have recently updated the whole stack of our IIIF implementation discovering that the IIIF manifest generated after the merge of my PR #6 is not well managed by UV.

Specifically the commit 
https://github.com/dbmdz/iiif-presentation-api/pull/6/commits/346d9fc53b9b58d2c45840a0ff2b66bfacc68398
change the json serialization so that services are now exposed in JSON with their "plural" nature (services instead of service). Looking the IIIF specification I think that this is our fault not something to address to UV. Do you agree?
Which is the best way to fix that? should we rollback the commit or should we annotate the services attribute so to be serialized as service instead that it plural form?

**Comment by jbaiter** [comment]
I just pushed a fix for this. It also adds support for multiple manifests to the `Service` and `Thumbnail` classes, which previously only supported a single service.
