### ISSUE TITLE
Sequence constructor: id, label(?)

### ISSUE THREAD

**Issue by ksclarke** [dbmdz/iiif-presentation-api#2]
Hi,

First, thanks for this library! I've started working with it and have noticed a general pattern in the model's constructors (where id and label can be passed in together in the creation of the object). Sequence seems to be an exception, though, as it just takes label.  I was wondering about changing its constructor to be <code>new Sequence(id, label)</code> instead.  What do you think?  Just a suggestion.  Thanks!

**Comment by datazuul** [comment]
according to http://iiif.io/api/presentation/2.0/#b-summary-of-metadata-requirements Sequence and Annotation are the only ressources that have an optional id. I tend to offer a constructor only with required fields. but for convenience I added constructors in sequence and annotation classes.

**Comment by ksclarke** [comment]
Ah, okay, thanks for the explanation!
