### ISSUE TITLE
seeAlso properties not supported in the IIIF presentation model

### ISSUE THREAD

**Issue by nfreire** [dbmdz/iiif-presentation-api#4]
The seeAlso properties 'profile', 'format' and 'label' are not supported by the model.
http://iiif.io/api/presentation/2.1/#seealso

de.digitalcollections.iiif.presentation.model.api.v2_0_0.IiifResource allows only for a String representing the seeAlso.

**Comment by jbaiter** [comment]
Thanks for catching that! :-)

**Comment by nfreire** [comment]
That was very fast :)
Thanks a lot.
